### ISSUE TITLE
Integrated Webpa client support in RDKB Emulator and RPI 

### ISSUE THREAD

**Issue by kpandu123** [Comcast/parodus2ccsp#22]
Introduced "RDKB_EMU" and "PLATFORM_RASPBERRYPI" Macros in code base to enable webpa client support in RDKB Emulator and RPI.

**Comment by shilpa24balaji** [comment]
Please submit pull request for these changes

**Comment by kpandu123** [comment]
Added https://github.com/Comcast/parodus2ccsp/pull/24

**Comment by shilpa24balaji** [comment]
#24 is merged now hence closing this issue
