### ISSUE TITLE
getchar() can loop forever if missing `q`

### ISSUE THREAD

**Issue by schmidtw** [Comcast/parodus2ccsp#43]
https://github.com/Comcast/parodus2ccsp/blob/a0cb303c097e83aa1a58854457ac1a6b44aba456/source/broadband/ssp_main.c#L141

If `STDIN` doesn't contain a `q` it looks like this will loop forever.

**Comment by shilpa24balaji** [comment]
This seems intentional as it is supposed to be a daemon.

**Comment by schmidtw** [comment]
I agree.
